<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdvertisingMatterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('advertisement_matters')->insert([
            [
                'advertising_matter'   => 'Pacific Breeze Soft Drink TVC',
                'slug'                 => 'pacific-breeze-soft-drink-tvc',
                'description'          => 'A vibrant TV commercial showing young people enjoying a new soft drink on PNG beaches.',
                'casts'   => 'John Kila',
                'director'             => 'Maria Sungi',
                'producer'             => 'Ocean Wave Media',
                'production_company'   => 'Island Vision Studios',
                'client_company'       => 'Pacific Breeze Beverages Ltd',
                'release_year'         => 2023,
                'duration'             => 30,
                'genre'                => 'Commercial',
                'language'             => 'English',
                'has_subtitle'         => true,
                'brand_promoted'       => 'Pacific Breeze',
                'product_promoted'     => 'Carbonated Soft Drink',
                'theme'                => 'Celebration of youth, friendship and tropical lifestyle.',
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
            [
                'advertising_matter'   => 'Healthy Choice Rice TVC',
                'slug'                 => 'healthy-choice-rice-tvc',
                'description'          => 'Family-oriented TV ad promoting nutritious rice for everyday PNG households.',
                'casts'   => 'Lucy Aihi',
                'director'             => 'Peter Wari',
                'producer'             => 'Highlands Creative House',
                'production_company'   => 'Kumul Filmworks',
                'client_company'       => 'Healthy Choice Foods PNG',
                'release_year'         => 2022,
                'duration'             => 45,
                'genre'                => 'Commercial',
                'language'             => 'Tok Pisin',
                'has_subtitle'         => true,
                'brand_promoted'       => 'Healthy Choice',
                'product_promoted'     => 'Long Grain Rice',
                'theme'                => 'Family togetherness, nutrition and local culture.',
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
            [
                'advertising_matter'   => 'CityBank Mobile App Launch Ad',
                'slug'                 => 'citybank-mobile-app-launch-ad',
                'description'          => 'Digital and TV campaign showcasing features of a new mobile banking app.',
                'casts'   => 'Kelvin Nali',
                'director'             => 'Angela Ramo',
                'producer'             => 'Urban Screen Media',
                'production_company'   => 'Port Moresby Creative Hub',
                'client_company'       => 'CityBank PNG',
                'release_year'         => 2024,
                'duration'             => 60,
                'genre'                => 'Commercial',
                'language'             => 'English',
                'has_subtitle'         => false,
                'brand_promoted'       => 'CityBank',
                'product_promoted'     => 'Mobile Banking Application',
                'theme'                => 'Financial inclusion, convenience and security in banking.',
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
            [
                'advertising_matter'   => 'PNG Tourism “Discover Our Islands”',
                'slug'                 => 'png-tourism-discover-our-islands',
                'description'          => 'Scenic advertisement promoting tourism spots across Papua New Guinea.',
                'casts'   => 'Tourist Ensemble Cast',
                'director'             => 'Simon Koivi',
                'producer'             => 'Coral Reef Productions',
                'production_company'   => 'Pacific Horizon Films',
                'client_company'       => 'PNG Tourism Promotion Authority',
                'release_year'         => 2021,
                'duration'             => 90,
                'genre'                => 'Promotional',
                'language'             => 'English',
                'has_subtitle'         => false,
                'brand_promoted'       => 'PNG Tourism',
                'product_promoted'     => 'Tourism Destinations in PNG',
                'theme'                => 'National pride, cultural diversity and eco-tourism.',
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
            [
                'advertising_matter'   => 'Safe Road PNG Awareness Spot',
                'slug'                 => 'safe-road-png-awareness-spot',
                'description'          => 'Public awareness TVC about safe driving and road rules.',
                'casts'   => 'Police Traffic Unit Cast',
                'director'             => 'Michael Manu',
                'producer'             => 'Community Vision Media',
                'production_company'   => 'Highway Films PNG',
                'client_company'       => 'National Road Safety Council',
                'release_year'         => 2020,
                'duration'             => 40,
                'genre'                => 'Public Service Announcement',
                'language'             => 'Tok Pisin',
                'has_subtitle'         => true,
                'brand_promoted'       => 'Safe Road PNG',
                'product_promoted'     => 'Road Safety Campaign',
                'theme'                => 'Responsible driving, law enforcement and community safety.',
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
            [
                'advertising_matter'   => 'Fresh Harvest Cooking Oil TVC',
                'slug'                 => 'fresh-harvest-cooking-oil-tvc',
                'description'          => 'Kitchen-themed commercial featuring a mother cooking for her family.',
                'casts'   => 'Mary Lohia',
                'director'             => 'Jonathan Peni',
                'producer'             => 'Hauslain Media',
                'production_company'   => 'Sunrise Film Studio',
                'client_company'       => 'Fresh Harvest Foods Ltd',
                'release_year'         => 2023,
                'duration'             => 30,
                'genre'                => 'Commercial',
                'language'             => 'Tok Pisin',
                'has_subtitle'         => false,
                'brand_promoted'       => 'Fresh Harvest',
                'product_promoted'     => 'Cooking Oil',
                'theme'                => 'Home cooking, quality ingredients and family wellbeing.',
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
            [
                'advertising_matter'   => 'Kumul Telecom 4G Network Ad',
                'slug'                 => 'kumul-telecom-4g-network-ad',
                'description'          => 'Youth-focused ad highlighting faster internet and connectivity.',
                'casts'   => 'Youth Ensemble Cast',
                'director'             => 'Derrick Wane',
                'producer'             => 'Skyline Productions',
                'production_company'   => 'Kumul Creative Studio',
                'client_company'       => 'Kumul Telecom PNG',
                'release_year'         => 2022,
                'duration'             => 35,
                'genre'                => 'Commercial',
                'language'             => 'English',
                'has_subtitle'         => false,
                'brand_promoted'       => 'Kumul Telecom',
                'product_promoted'     => '4G Mobile Data Service',
                'theme'                => 'Digital lifestyle, speed and nationwide coverage.',
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
            [
                'advertising_matter'   => 'GreenLife Fertilizer Radio & TV Ad',
                'slug'                 => 'greenlife-fertilizer-radio-tv-ad',
                'description'          => 'Mixed-media campaign encouraging local farmers to use eco-friendly fertilizer.',
                'casts'   => 'Farmer Ensemble Cast',
                'director'             => 'Linda Pange',
                'producer'             => 'AgroMedia PNG',
                'production_company'   => 'Valley View Films',
                'client_company'       => 'GreenLife Agriculture Ltd',
                'release_year'         => 2021,
                'duration'             => 45,
                'genre'                => 'Commercial',
                'language'             => 'Tok Pisin',
                'has_subtitle'         => true,
                'brand_promoted'       => 'GreenLife',
                'product_promoted'     => 'Organic Fertilizer',
                'theme'                => 'Agricultural growth, sustainability and rural development.',
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
            [
                'advertising_matter'   => 'Pacific Health Insurance Family Plan',
                'slug'                 => 'pacific-health-insurance-family-plan',
                'description'          => 'Emotional advertisement about health security for PNG families.',
                'casts'   => 'Family Ensemble Cast',
                'director'             => 'Henry Garo',
                'producer'             => 'Blue Shield Media',
                'production_company'   => 'Harbour City Films',
                'client_company'       => 'Pacific Health Insurance',
                'release_year'         => 2023,
                'duration'             => 60,
                'genre'                => 'Commercial',
                'language'             => 'English',
                'has_subtitle'         => true,
                'brand_promoted'       => 'Pacific Health',
                'product_promoted'     => 'Family Health Insurance Plan',
                'theme'                => 'Healthcare, financial protection and family security.',
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
            [
                'advertising_matter'   => 'Clean City Anti-Litter Campaign',
                'slug'                 => 'clean-city-anti-litter-campaign',
                'description'          => 'Public service advertisement discouraging littering in urban areas.',
                'casts'   => 'Community Volunteers',
                'director'             => 'Rita Dom',
                'producer'             => 'Island Change Productions',
                'production_company'   => 'Street View Media',
                'client_company'       => 'Clean City Initiative PNG',
                'release_year'         => 2020,
                'duration'             => 30,
                'genre'                => 'Public Service Announcement',
                'language'             => 'Tok Pisin',
                'has_subtitle'         => false,
                'brand_promoted'       => 'Clean City',
                'product_promoted'     => 'Urban Cleanliness Campaign',
                'theme'                => 'Environmental responsibility, civic pride and community action.',
                'created_at'           => now(),
                'updated_at'           => now(),
            ],
        ]);
    }
}
