<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FilmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('films')->insert([
            [
                'film_title' => 'Inception',
                'slug' => 'inception',
                'main_actor_actress' => 'Leonardo DiCaprio',
                'director' => 'Christopher Nolan',
                'producer' => 'Emma Thomas',
                'production_company' => 'Warner Bros.',
                'release_year' => 2010,
                'genre' => 'Science Fiction',
                'language' => 'English',
                'duration' => 148,
                'subtitle' => 'Yes',
                'theme' => 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
                'film_type_id' => 1,
            ],
            [
                'film_title' => 'The Godfather',
                'slug' => 'the-godfather',
                'main_actor_actress' => 'Marlon Brando',
                'director' => 'Francis Ford Coppola',
                'producer' => 'Albert S. Ruddy',
                'production_company' => 'Paramount Pictures',
                'release_year' => 1972,
                'genre' => 'Crime',
                'language' => 'English',
                'duration' => 175,
                'subtitle' => 'No',
                'theme' => 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
                'film_type_id' => 2,
            ],
            [
                'film_title' => 'Spirited Away',
                'slug' => 'spirited-away',
                'main_actor_actress' => 'Rumi Hiiragi',
                'director' => 'Hayao Miyazaki',
                'producer' => 'Toshio Suzuki',
                'production_company' => 'Studio Ghibli',
                'release_year' => 2001,
                'genre' => 'Animation',
                'language' => 'Japanese',
                'duration' => 125,
                'subtitle' => 'Yes',
                'theme' => 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts.',
                'film_type_id' => 3,
            ],
            [
                'film_title' => 'Parasite',
                'slug' => 'parasite',
                'main_actor_actress' => 'Song Kang-ho',
                'director' => 'Bong Joon-ho',
                'producer' => 'Kwak Sin-ae',
                'production_company' => 'CJ Entertainment',
                'release_year' => 2019,
                'genre' => 'Thriller',
                'language' => 'Korean',
                'duration' => 132,
                'subtitle' => 'Yes',
                'theme' => 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
                'film_type_id' => 4,    
            ],
            [
                'film_title' => 'The Dark Knight',
                'slug' => 'the-dark-knight',
                'main_actor_actress' => 'Christian Bale',
                'director' => 'Christopher Nolan',
                'producer' => 'Emma Thomas',
                'production_company' => 'Warner Bros.',
                'release_year' => 2008,
                'genre' => 'Action',
                'language' => 'English',
                'duration' => 152,
                'subtitle' => 'No',
                'theme' => 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
                'film_type_id' => 1,
            ],
            [
                'film_title' => 'Amélie',
                'slug' => 'amelie',
                'main_actor_actress' => 'Audrey Tautou',
                'director' => 'Jean-Pierre Jeunet',
                'producer' => 'Claudie Ossard',
                'production_company' => 'UGC Fox Distribution',
                'release_year' => 2001,
                'genre' => 'Romantic Comedy',
                'language' => 'French',
                'duration' => 122,
                'subtitle' => 'Yes',
                'theme' => 'Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.',
                'film_type_id' => 5,
            ],
            [
                'film_title' => 'Interstellar',
                'slug' => 'interstellar',
                'main_actor_actress' => 'Matthew McConaughey',
                'director' => 'Christopher Nolan',
                'producer' => 'Emma Thomas',
                'production_company' => 'Paramount Pictures',
                'release_year' => 2014,
                'genre' => 'Science Fiction',
                'language' => 'English',
                'duration' => 169,
                'subtitle' => 'No',
                'theme' => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
                'film_type_id' => 1,
            ],
            [
                'film_title' => 'La La Land',
                'slug' => 'la-la-land',
                'main_actor_actress' => 'Emma Stone',
                'director' => 'Damien Chazelle',
                'producer' => 'Fred Berger',
                'production_company' => 'Summit Entertainment',
                'release_year' => 2016,
                'genre' => 'Musical',
                'language' => 'English',
                'duration' => 128,
                'subtitle' => 'No',
                'theme' => 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
                'film_type_id' => 5,
            ],
            [
                'film_title' => 'Crouching Tiger, Hidden Dragon',
                'slug' => 'crouching-tiger-hidden-dragon',
                'main_actor_actress' => 'Chow Yun-fat',
                'director' => 'Ang Lee',
                'producer' => 'Ang Lee',
                'production_company' => 'Columbia Pictures',
                'release_year' => 2000,
                'genre' => 'Martial Arts',
                'language' => 'Mandarin',
                'duration' => 120,
                'subtitle' => 'Yes',
                'theme' => 'A young Chinese warrior steals a sword from a famed swordsman and then escapes into a world of romantic adventure with a mysterious man.',
                'film_type_id' => 6,
            ],
            [
                'film_title' => 'The Shawshank Redemption',
                'slug' => 'the-shawshank-redemption',
                'main_actor_actress' => 'Tim Robbins',
                'director' => 'Frank Darabont',
                'producer' => 'Niki Marvin',
                'production_company' => 'Columbia Pictures',
                'release_year' => 1994,
                'genre' => 'Drama',
                'language' => 'English',
                'duration' => 142,
                'subtitle' => 'No',
                'theme' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
                'film_type_id' => 2,
            ],
            [
                'film_title' => 'City of God',
                'slug' => 'city-of-god',
                'main_actor_actress' => 'Alexandre Rodrigues',
                'director' => 'Fernando Meirelles',
                'producer' => 'Andrea Barata Ribeiro',
                'production_company' => 'O2 Filmes',
                'release_year' => 2002,
                'genre' => 'Crime',
                'language' => 'Portuguese',
                'duration' => 130,
                'subtitle' => 'Yes',
                'theme' => 'In the slums of Rio, two kids\' paths diverge as one struggles to become a photographer and the other a kingpin.',
                'film_type_id' => 4,
            ],
            [
                'film_title' => 'The Lion King',
                'slug' => 'the-lion-king',
                'main_actor_actress' => 'Matthew Broderick',
                'director' => 'Roger Allers',
                'producer' => 'Don Hahn',
                'production_company' => 'Walt Disney Pictures',
                'release_year' => 1994,
                'genre' => 'Animation',
                'language' => 'English',
                'duration' => 88,
                'subtitle' => 'No',
                'theme' => 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
                'film_type_id' => 3,
            ],
            [
                'film_title' => 'Titanic',
                'slug' => 'titanic',
                'main_actor_actress' => 'Kate Winslet',
                'director' => 'James Cameron',
                'producer' => 'James Cameron',
                'production_company' => '20th Century Fox',
                'release_year' => 1997,
                'genre' => 'Romance',
                'language' => 'English',
                'duration' => 195,
                'subtitle' => 'No',
                'theme' => 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
                'film_type_id' => 5,
            ],
            [
                'film_title' => 'Oldboy',
                'slug' => 'oldboy',
                'main_actor_actress' => 'Choi Min-sik',
                'director' => 'Park Chan-wook',
                'producer' => 'Lim Seung-yong',
                'production_company' => 'Show East',
                'release_year' => 2003,
                'genre' => 'Thriller',
                'language' => 'Korean',
                'duration' => 120,
                'subtitle' => 'Yes',
                'theme' => 'After being kidnapped and imprisoned for fifteen years, Oh Dae-su is released, only to find that he must find his captor in five days.',
                'film_type_id' => 4,
            ],
            [
                'film_title' => 'Pan\'s Labyrinth',
                'slug' => 'pans-labyrinth',
                'main_actor_actress' => 'Ivana Baquero',
                'director' => 'Guillermo del Toro',
                'producer' => 'Alfonso Cuarón',
                'production_company' => 'Picturehouse',
                'release_year' => 2006,
                'genre' => 'Fantasy',
                'language' => 'Spanish',
                'duration' => 118,
                'subtitle' => 'Yes',
                'theme' => 'In the aftermath of the Spanish Civil War, young Ofelia meets a mysterious faun who sets her on a path to reclaim her royal heritage.',
                'film_type_id' => 6,
            ],
            [
                'film_title' => 'Gladiator',
                'slug' => 'gladiator',
                'main_actor_actress' => 'Russell Crowe',
                'director' => 'Ridley Scott',
                'producer' => 'Douglas Wick',
                'production_company' => 'DreamWorks Pictures',
                'release_year' => 2000,
                'genre' => 'Action',
                'language' => 'English',
                'duration' => 155,
                'subtitle' => 'No',
                'theme' => 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
                'film_type_id' => 1,
            ]
        ]);
    }
}
